name: tide-web-apps feature comment Workflow
on: 
  pull_request:
    types:
      - opened
      - reopened
    branches: [main, bugfix/*, feature/*, hotfix/*]
jobs:
  comment_pull_request:
    name: Comment pull request
    runs-on: ubuntu-latest
    container:
      image: python:3.6
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_URL: ${{ github.event.pull_request.comments_url }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          echo $BRANCH
          bin/comment-urls.sh
          
          
