name: Greetings

on: [pull_request, issues]
env:
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
jobs:
  deploy_feature_branch:
    name: Deploy feature branch
    runs-on: ubuntu-latest
    container:
      image: python:3.6

    steps:
      - name: Github checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run script
        run: |
          url="test"
          bin/deploy.sh
      - name: Add comment to PR
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl 
          -X POST 
          $URL 
          -H "Content-Type: application/json" 
          -H "Authorization: token $GITHUB_TOKEN" 
          --data '{ "body": "blah blah" }'
