name: Greetings

on: [pull_request, issues]

jobs:
  deploy_feature_branch:
    name: Deploy feature branch
    runs-on: ubuntu-latest
    container:
      image: python:3.6

    steps:
      - name: Run script
        run: |
          bin/deploy.sh
