name: Greetings

on: [pull_request, issues]
env:
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
jobs:
  deploy_feature_branch:
    name: Deploy feature branch
    runs-on: ubuntu-latest
    container:
      image: python:3.6

    steps:
      - name: Github checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run script
        run: |
          bin/deploy.sh
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
