name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Run script
      - uses: actions/github-script@v3
        with: 
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              bin/deploy.sh
              github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: '👋 Thanks for reporting!'
              })
